version: '3'
services:
  api-server:
    image: wetalk-local
    ports:
      - "5510:5510"
    networks:
      - WT-local
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports: 
      - "27018:27017"
    networks:
      - WT-local
    volumes:
      - mongo-data:/data/connection
networks:
  WT-local:
    driver: bridge
volumes:
  mongo-data:
    driver: local
